(function(){
 const api=window.WaoData,login=document.getElementById('loginView'),workspace=document.getElementById('workspace'),form=document.getElementById('productForm');let products=[],images=[];
 const message=(text,error=false)=>{const node=document.getElementById('formMessage');node.textContent=text;node.style.color=error?'#a53b32':'#3e8b62'};
 function showWorkspace(){login.hidden=true;workspace.hidden=false;window.scrollTo({top:0,left:0,behavior:'instant'});loadProducts()}
 if(api.session())showWorkspace();
 document.getElementById('loginForm').addEventListener('submit',async e=>{e.preventDefault();const node=document.getElementById('loginMessage');node.textContent='正在验证…';try{await api.signIn(e.target.email.value,e.target.password.value);showWorkspace()}catch(err){node.textContent=err.message}});
 document.getElementById('logoutBtn').addEventListener('click',()=>{api.signOut();location.reload()});
 async function loadProducts(){try{products=await api.listProducts(true);renderList()}catch(err){message(err.message,true)}}
 function renderList(){const q=document.getElementById('productSearch').value.trim().toLowerCase(),series=document.getElementById('seriesFilter').value;const filtered=products.filter(p=>(!q||`${p.name} ${p.sku}`.toLowerCase().includes(q))&&(!series||p.collection===series));document.getElementById('productTotal').textContent=`${products.length} 款产品`;document.getElementById('productList').innerHTML=filtered.map(p=>`<button class="product-row" type="button" data-id="${p.id}"><img src="${p.images?.[0]||'assets/logo-icon.png'}" alt=""><span><strong>${escapeHtml(p.name)}</strong><small>${escapeHtml(p.sku)} · ${escapeHtml(p.collection==='Fuyi Collection'?'Versailles':p.collection)}</small></span><i class="status-dot ${p.status}" title="${p.status==='published'?'已发布':'草稿'}"></i></button>`).join('')||'<p style="padding:24px;color:#687386">没有匹配产品</p>';document.querySelectorAll('.product-row').forEach(b=>b.addEventListener('click',()=>editProduct(products.find(p=>p.id===b.dataset.id))))}
 const escapeHtml=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 ['productSearch','seriesFilter'].forEach(id=>document.getElementById(id).addEventListener(id==='productSearch'?'input':'change',renderList));
 function editProduct(p={}){document.getElementById('editorEmpty').hidden=true;form.hidden=false;form.reset();for(const [key,val] of Object.entries(p))if(form.elements[key]&&val!=null)form.elements[key].value=val;images=[...(p.images||[])];form.elements.sort_order.value=p.sort_order||0;document.getElementById('editorMode').textContent=p.id?'编辑产品':'新建产品';document.getElementById('editorTitle').textContent=p.name||'未命名产品';document.getElementById('deleteBtn').hidden=!p.id;renderImages();message('')}
 document.getElementById('newProductBtn').addEventListener('click',()=>editProduct());form.elements.name.addEventListener('input',()=>document.getElementById('editorTitle').textContent=form.elements.name.value||'未命名产品');
 function renderImages(){document.getElementById('imageGrid').innerHTML=images.map((src,i)=>`<div class="image-item"><img src="${src}" alt="产品图 ${i+1}"><button type="button" data-remove="${i}" aria-label="移除图片">×</button></div>`).join('');document.querySelectorAll('[data-remove]').forEach(b=>b.addEventListener('click',()=>{images.splice(Number(b.dataset.remove),1);renderImages()}))}
 async function addFiles(files){const valid=[...files].filter(f=>/^image\/(jpeg|png|webp)$/.test(f.type)&&f.size<=8*1024*1024);if(images.length+valid.length>5)return message('每款产品最多上传 5 张图片。',true);if(valid.length!==files.length)return message('仅支持 JPG、PNG、WebP，且单张不超过 8MB。',true);const progress=document.getElementById('uploadProgress');progress.hidden=false;message(`正在上传 0 / ${valid.length}，请勿关闭页面…`);try{const key=(form.elements.sku.value||crypto.randomUUID()).toLowerCase().replace(/[^a-z0-9-]/g,'-');for(let i=0;i<valid.length;i++){images.push(await api.uploadImage(valid[i],key));progress.firstElementChild.style.width=`${((i+1)/valid.length)*100}%`;renderImages();message(`正在上传 ${i+1} / ${valid.length}…`)}message('图片上传完成。')}catch(err){message(err.message,true)}finally{setTimeout(()=>{progress.hidden=true;progress.firstElementChild.style.width='0'},500)}}
 const input=document.getElementById('imageInput'),drop=document.getElementById('dropzone');input.addEventListener('change',()=>addFiles(input.files));['dragenter','dragover'].forEach(n=>drop.addEventListener(n,e=>{e.preventDefault();drop.classList.add('dragging')}));['dragleave','drop'].forEach(n=>drop.addEventListener(n,e=>{e.preventDefault();drop.classList.remove('dragging')}));drop.addEventListener('drop',e=>addFiles(e.dataTransfer.files));
 async function save(status){if(!form.reportValidity())return;if(!images.length)return message('请至少上传 1 张产品图。',true);const data=Object.fromEntries(new FormData(form));data.price=data.price?Number(data.price):null;data.sort_order=Number(data.sort_order)||0;data.images=images;data.status=status;delete data.id;if(form.elements.id.value)data.id=form.elements.id.value;message('正在保存…');try{const saved=await api.saveProduct(data);await loadProducts();if(status==='published'){form.hidden=true;document.getElementById('editorEmpty').hidden=false;document.querySelector('#editorEmpty h2').textContent='产品已发布';document.querySelector('#editorEmpty p').textContent='已返回产品列表，可继续新建或选择产品编辑。';window.scrollTo({top:0,left:0,behavior:'smooth'})}else{message('草稿已保存。');editProduct(saved)}}catch(err){message(err.message,true)}}
 document.getElementById('saveDraftBtn').addEventListener('click',()=>save('draft'));document.getElementById('publishBtn').addEventListener('click',()=>save('published'));document.getElementById('deleteBtn').addEventListener('click',async()=>{const id=form.elements.id.value;if(!id||!confirm('确定删除这款产品？已上传图片仍会保留在素材库中。'))return;try{await api.deleteProduct(id);form.hidden=true;document.getElementById('editorEmpty').hidden=false;await loadProducts()}catch(err){message(err.message,true)}});
 if(!api.configured)document.getElementById('loginMessage').textContent='尚未配置 Supabase。请参考 README-BACKEND.md 完成首次连接。';
})();
